### ISSUE TITLE
Crash with PHP Fatal error   thrown in /root/scripts/pfsense_zbx.php on line 667 (agent 4.0/5.4 tested and pfSense CE 2.6.0)

### ISSUE THREAD

**Issue by mrnafanya** [rbicelli/pfsense-zabbix-template#114]
Crash report details:

PHP Errors:
[19-Mar-2022 15:12:56 Europe] PHP Fatal error:  Uncaught Error: Call to undefined function get_ipsecifnum() in /root/scripts/pfsense_zbx.php:667
Stack trace:
#0 /root/scripts/pfsense_zbx.php(579): pfz_ipsec_status('3')
#1 /root/scripts/pfsense_zbx.php(1273): pfz_ipsec_ph1('3', 'status')
#2 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 667

**Comment by mrnafanya** [comment]
Duplicate of the previous post for the same issue.
