### ISSUE TITLE
PHP error thrown

### ISSUE THREAD

**Issue by postilion** [rbicelli/pfsense-zabbix-template#136]
Upon installing latest scripts on pfSense+ v23.01 got this error:
```
PHP ERROR: Type: 1, File: /root/scripts/pfsense_zbx.php, Line: 978, Message: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /root/scripts/pfsense_zbx.php:978
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1024): pfz_dhcp_get('failover')
#1 /root/scripts/pfsense_zbx.php(1037): pfz_dhcp_check_failover()
#2 /root/scripts/pfsense_zbx.php(1338): pfz_dhcp('failover', NULL)
#3 {main}
thrown @ 2023-03-09 16:19:00
```

Still investigating.
-nic

**Comment by rbicelli** [comment]
Hello, this is a known behavior. It's because in pfsense+ functions related to dhcp leases are changed.
For now this could be mitigated disabling the item "DHCP Failover Pool Problems".

**Comment by postilion** [comment]
Thanks! Done.
-nic
