### ISSUE TITLE
Crash report begins.  Anonymous machine information:

### ISSUE THREAD

**Issue by eduardo-eller** [rbicelli/pfsense-zabbix-template#166]
Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT amd64 1400094 #1 plus-RELENG_23_09_1-n256200-3de1e293f3a: Wed Dec  6 21:00:32 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-Plus-snapshots-23_09_1-main/obj/amd64/Obhu6gXB/var/jenkins/workspace/pfSense-Plus-snapshots-23_09_1

Crash report details:

PHP Errors:
[28-Feb-2024 18:44:34 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1278): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1646): pfz_get_ref_cert_algo('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237
[28-Feb-2024 18:44:39 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1254): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1649): pfz_get_ref_cert_algo_len('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237
[28-Feb-2024 18:44:44 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1260): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1652): pfz_get_ref_cert_algo_bits('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237
[28-Feb-2024 18:59:34 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1278): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1646): pfz_get_ref_cert_algo('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237
[28-Feb-2024 18:59:39 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1254): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1649): pfz_get_ref_cert_algo_len('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237
[28-Feb-2024 18:59:44 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1260): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1652): pfz_get_ref_cert_algo_bits('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237
[28-Feb-2024 19:14:35 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1278): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1646): pfz_get_ref_cert_algo('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237
[28-Feb-2024 19:14:39 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1254): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1649): pfz_get_ref_cert_algo_len('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237
[28-Feb-2024 19:14:44 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1260): pfz_get_cert_pkey_info(3)
#2 /root/scripts/pfsense_zbx.php(1652): pfz_get_ref_cert_algo_bits('65539')
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 1237

No FreeBSD crash data found.

**Comment by rbicelli** [comment]
Hopefully fixed with latest commit
