### ISSUE TITLE
Zabbix Error on Phase1 and 2 status

### ISSUE THREAD

**Issue by f3lipp3** [rbicelli/pfsense-zabbix-template#175]
I'm getting this issue. Can anyone help? Zabbix 6

Fatal error: Uncaught Error: Call to undefined function get_ipsecifnum() in /root/scripts/pfsense_zbx.php:668
Stack trace:
#0 /root/scripts/pfsense_zbx.php(639): pfz_ipsec_status('1', '3', 'state')
#1 /root/scripts/pfsense_zbx.php(1277): pfz_ipsec_ph2('1.3', 'status')
#2 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 668
PHP ERROR: Type: 1, File: /root/scripts/pfsense_zbx.php, Line: 668, Message: Uncaught Error: Call to undefined function get_ipsecifnum() in /root/scripts/pfsense_zbx.php:668
Stack trace:
#0 /root/scripts/pfsense_zbx.php(639): pfz_ipsec_status('1', '3', 'state')
#1 /root/scripts/pfsense_zbx.php(1277): pfz_ipsec_ph2('1.3', 'status')
#2 {main}
  thrown

**Comment by GuillaumeHullin** [comment]
What's your version of pfSense?

**Comment by f3lipp3** [comment]
> What's your version of pfSense?

FreeBSD BRITFW-SECONDARY.pfSense.ORACLE 14.0-CURRENT FreeBSD 14.0-CURRENT amd64 1400094 #1 RELENG_2_7_2-n255948-8d2b56da39c: Wed Dec 6 20:45:47 UTC 2023 root@freebsd:/var/jenkins/workspace/pfSense-CE-snapshots-2_7_2-main/obj/amd64/StdASW5b/var/jenkin
